# Construct the average Industry concentration and Profit margins (PMs) for the firms
# in all three-digit industries each year SIC3 YEAR (note that you need to construct the
# variable SIC3 by taking the first three digits of an SIC code). PMs are defined above. By
# averaging the PMs, weight with SLS.
# Define Industry concentration as the fraction of sales generated by the 5 largest firms in
# the industry each year relative to the total amount of sales generated by all firms in the
# industry that year. More specifically:
# 1. Sort all firms based on their sales (SLS) in a descending order by SIC3 YEAR.
# 2. Identify the 5 largest firms in terms of SLS (if there are less than 5 years, identify all of
# them).
# 3. Construct